### ISSUE TITLE
Size of Elliptic Transform Source in MultiBox and Crash

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-biop-tools#10]
The Elliptic Source appear super small:

<img width="149" alt="image" src="https://user-images.githubusercontent.com/2157566/120292985-1add7900-c2c5-11eb-93ac-a1ae4740d966.png">

I think somethings off with its "size", which is hard to say what it should be, I guess, because it can change....

In addition, when resizing the BDV window the multi-box overlay crashed with an error message, which I unfortunately did not record. I could not yet reproduce the error.

**Comment by NicoKiaru** [comment]
For warped sources or 'realrandomaccessible' sources in general, I don't know where and how the bounding box is computed. I guess it takes the affine transform and the interval of the source ?

**Comment by tischi** [comment]
Yes, I think so. 
Maybe we can improve the interval?
But how....
One could use the same interval as for the "target source" that is to be transformed, but we don't know this upon creation of the Ellipsoid...

**Comment by NicoKiaru** [comment]
Related to https://github.com/BIOP/bigdataviewer-biop-tools/issues/14. I think we can't fix it here.

**Comment by NicoKiaru** [comment]
I think the crash part has been fixed however in BigWarp

**Comment by NicoKiaru** [comment]
For the elliptic source size on display, see https://github.com/BIOP/bigdataviewer-biop-tools/issues/14
