### ISSUE TITLE
Load and save ellipsoid transforms

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-biop-tools#19]
@NicoKiaru can you already save and load EllipsoidTransforms?

**Comment by NicoKiaru** [comment]
Normally yes because there's an adapter:

https://github.com/BIOP/bigdataviewer-biop-tools/blob/master/src/main/java/bdv/util/Elliptical3DTransformRealTransformAdapter.java

**Comment by tischi** [comment]
OK, can I try to add something the UI such that users can make use of this?
Or is there already some `Save` button for this?

**Comment by NicoKiaru** [comment]
Sure, to save the transformit works like this:

`ScijavaGsonHelper.getGson(scijavaContext).toJson(transform, RealTransform.class);`

**Comment by tischi** [comment]
Here's the [PR](https://github.com/BIOP/bigdataviewer-biop-tools/pull/21)
