### ISSUE TITLE
Ellipsoid transform names

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-biop-tools#26]
@NicoKiaru 

Is there a way to give names (Strings) to the Ellipsoid transforms?
Without it is very had to know which one selects in the drop-down.

**Comment by NicoKiaru** [comment]
We can probably add a toString method

**Comment by NicoKiaru** [comment]
Done in https://github.com/BIOP/bigdataviewer-biop-tools/commit/9c73efea9ddb23a2852aa5b5f441ed6d70c34c92
