### ISSUE TITLE
Export ImagePlus with more than one time point crashes

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-biop-tools#30]
@NicoKiaru 

The exporter seems to have an issue with images that have more than one timepoint.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/2157566/136948518-9e2504ed-3552-4cb5-b21c-6eb2f3144bb0.png">

Do you have time to fix this or should I give it a go?

**Comment by tischi** [comment]
Will you have a look or shall I?

**Comment by tischi** [comment]
I realize now that in fact you are returning `numFrames`, which means that maybe the name of the method is wrong? `getMaxTimepoint` should be `getNumTimepoints`?!

**Comment by tischi** [comment]
@NicoKiaru 
Just add 1:

was:
`for (int tp=previous;tp<iFrame;tp++)`

should be:
`for (int tp=previous;tp<iFrame+1;tp++)`

**Comment by tischi** [comment]
@NicoKiaru Are those fixes already on the update site?

**Comment by NicoKiaru** [comment]
No the bigdataviewer-playground update site is old. You can use ABBA for now. But there's a paper coming so I need to update the bigdataviewer-playground update site this week.

**Comment by tischi** [comment]
@NicoKiaru On ABBA update site the example is still wrong:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/2157566/145405824-44a755ec-24fb-44f7-8726-18bbf1ae7de8.png">

The examples should be zero based.

**Comment by NicoKiaru** [comment]
oki doki
