### ISSUE TITLE
Improve DemoEllipticalSource 

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-biop-tools#35]
@NicoKiaru
Running the `DemoEllipticalSource` class as is does not work, because the default parameters for the `Elliptic3DTransformCreatorCommand` are just `0.0`. 
Do you happen to know some parameters that work? 
Then I could try to change the code to call the command with those parameters.

**Comment by NicoKiaru** [comment]
Hi @tischi , 

I've modified it in the 'fusewarp' branch.
I plan to merge to branch very soon

**Comment by NicoKiaru** [comment]
I've pushed it to master. I wanted to check a few things, but let's hope it works
