### ISSUE TITLE
Fuse BigStitcher to OME-TIFF: Rounded numbers in GUI

### ISSUE THREAD

**Issue by lacan** [BIOP/bigdataviewer-biop-tools#40]
![image](https://user-images.githubusercontent.com/319932/174570320-41dd69b6-e9b8-4e6d-803e-32cefd731497.png)
the Vox_size and ratio record correct floating numbers but do not display them properly.

**Comment by NicoKiaru** [comment]
Done in https://github.com/BIOP/bigdataviewer-biop-tools/commit/79810d546885e0ea114a3761565f83b2f768f138 by removing them in the interface after simplification
