### ISSUE TITLE
Rotation3DTransformCommand does not seem to do anything

### ISSUE THREAD

**Issue by manerotoni** [BIOP/bigdataviewer-biop-tools#42]
Hello, 
I try to use the Rotation 3D Transform, but I do not have the impression that it does anything (no update of the image). [ Plugins › BigDataViewer-Playground › Sources › Transform › Rotation 3D Transform]
It complains that 
` 'sacs' is required but unset.`

Although in the list you do see a several sources.

Antonio

**Comment by NicoKiaru** [comment]
Thanks for letting me know, I will check this function.

**Comment by NicoKiaru** [comment]
This command only works for a so-called TransformedSource. You can create them via " BigDataViewer-Playground › Sources › Transform › Wrap as Transformed Source", but there's a bug I missed in another repo that I need to fix first. I'll do an update tomorrow with the fix hopefully

**Comment by NicoKiaru** [comment]
It's working now. Here's a gif showing how to do it:

![demo3dtransform](https://user-images.githubusercontent.com/20223054/174839904-e53d64ae-7e30-4baf-a32b-7b816c1bfae4.gif)


Let me know  if I can help further.

**Comment by manerotoni** [comment]
Hi @NicoKiaru,
great it works! Thanks! This is quite useful for us. 
Is there a way to apply the rotation command via a recorded Macro (any language)?

**Comment by NicoKiaru** [comment]
So the code for the rotation is here: https://github.com/BIOP/bigdataviewer-biop-tools/blob/982add6784fda9bfccaf00912b4214027d120601/src/main/java/ch/epfl/biop/scijava/command/transform/Rotation3DTransformCommand.java

It can be translated to groovy or jython, or the command can be called directly. However, what do you mean by 'applying'  the rotation ? Do you just need to change how it's displayed in BigDataViewer ?  Or do not need to compute a new stack with the image rotated and rasterized ?

**Comment by manerotoni** [comment]
I managed to call the run command and pass parameters in a script. Finding the right sacs is a little clumpsy but it does the job. 

Here a very short example, where I can then batch pass all my conversions. 

```
import ch.epfl.biop.scijava.command.transform.Rotation3DTransformCommand 
import sc.fiji.bdvpg.services.SourceAndConverterServices;
def sacs = SourceAndConverterServices.getSourceAndConverterService().getSourceAndConverters()
Rotation3DTransformCommand  Rot = new Rotation3DTransformCommand()
for (int i=2; i < 4; i++){
  Rot.sacs = sacs[i]
  Rot.rz = 20
  Rot.run()
}
```
