### ISSUE TITLE
Missing sources in bdvs

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/bigdataviewer-biop-tools#60]
following this commit (https://github.com/BIOP/bigdataviewer-biop-tools/commit/92bacfef8669e97ee7b5475c10cf4fc585d5252d), which takes into account the last modifications, I have a problem with the demo named AlphaDemoFull.

(Sorry I do not have tests, but I have plenty of demos that I run and check. I check that everything behaves correctly. Let's say it's 'manual integration tests').

This is how the demo looked just a commit before:

![Previously](https://github.com/BIOP/bigdataviewer-biop-tools/assets/20223054/30d869d8-4efb-43f1-8012-2709230903c7)

And this is how it looks with the commit 92bacfef8669:

![NewVolatileSource](https://github.com/BIOP/bigdataviewer-biop-tools/assets/20223054/8163b0e8-8fb9-4ee5-a9bd-c73b8f3d0b76)

As you can see, some sources are missing and appear randomly or by block.

I will need to bissect this further, and this'll take a bit of time.

@axtimwalde, @tpietzsch

**Comment by NicoKiaru** [comment]
With 
```
<bigdataviewer-core.version>10.4.13</bigdataviewer-core.version>
<bigdataviewer-vistools.version>1.0.0-beta-33</bigdataviewer-vistools.version>
```
and commit e20bebd62701d21d6d56 everything works fine.

With 1.0.0-beta-34 the conflicting VolatileSource shows up. 

I continue to dig.

**Comment by NicoKiaru** [comment]
Ok, if I rename "my" `VolatileSource` to `WrapVolatileSource` and use these dependencies:

```
<bigdataviewer-core.version>10.4.13</bigdataviewer-core.version>
<bigdataviewer-vistools.version>1.0.0-beta-34</bigdataviewer-vistools.version>
```

It still works fine. (commit https://github.com/BIOP/bigdataviewer-biop-tools/commit/e20bebd62701d21d6d56fe4f083949b957bc2af4 for this repo, and a modified temp commit for bigdataviewer-playground)

**Comment by NicoKiaru** [comment]
I can't disantangle everything easily, but the issue shows up when I put the BigWarp 9.1.0 dependency.

I can't work on this before mid next week. So I'm gonna have to keep shadowing BigWarp for the moment.

(@tischi no fix for now)

**Comment by axtimwalde** [comment]
This is truly strange.  To me, this looks as if the mipmap levels don't have the correct transformation, but there is no separate code in sandbox' WrapVolatileSource that does anything to the transformations.  It's all the same thing...

**Comment by NicoKiaru** [comment]
Ah yeah indeed no sub-resolution shows up. I'll keep this in mind, I think there's potentially some threading issues - like a transform object shared between threads while it should be copied.

**Comment by NicoKiaru** [comment]
This commit : https://github.com/saalfeldlab/bigwarp/commit/86d431e6f6874143d2d2455caebc860fd0c4f3fe
introduced the change I observe.

I did not look yet what's in it.

(@axtimwale, @bogovicj)

**Comment by NicoKiaru** [comment]
I thought the `tmpSrcTransform` introduced the behaviour, and I tried creating a new instance each it's required, but that's not changing anything. (even it is doesn't fix the issue, is it a good idea to keep one instance per object while your wrote this warning?):

> getSource can be called by multiple threads, so need ensure application of the transform is thread safe here by copying

**Comment by NicoKiaru** [comment]
Ok, I found the issue: I need to adopt the same logic than was has been done in BigWarp in 

https://github.com/BIOP/bigdataviewer-biop-tools/blob/92bacfef8669e97ee7b5475c10cf4fc585d5252d/src/main/java/bdv/util/source/alpha/AlphaSourceWarped.java#L56-L67

**Comment by NicoKiaru** [comment]
It's not sufficient, the change in https://github.com/saalfeldlab/bigwarp/commit/86d431e6f6874143d2d2455caebc860fd0c4f3fe
wreaks havoc in a lot of my repos regarding:
* concatenation of successive transforms
* making a source that blends many warped source efficiently

So, sorry to ask, but before I dig and spend a lot of time on this: do you have any clear benefit in this change ? Also have you tested whether it behaves correctly if you want to run BigWarp over an already WarpedSource (2xBigWarp). I need this in ABBA to apply successive transforms while keeping the ability to edit and cancel these successive layers.

**Comment by NicoKiaru** [comment]
(also the commit is 56 additions and 16 deletions)

**Comment by bogovicj** [comment]
Thanks for the recipe to reproduce the issue - I'm seeing the same thing and investigating ...

**Comment by NicoKiaru** [comment]
> Thanks for the recipe to reproduce the issue

I'm not sure I provided a good recipe... Don't hesitate if you want to set up a quick zoom meeting and avoid wasting time on some of my undocumented logic.

**Comment by bogovicj** [comment]
:smile: , so far so good.  I gave this a try today: the changes: https://github.com/bogovicj/bigdataviewer-biop-tools/commit/04ddc738f48d6d9dd820f289c79d741ec7d03d52

I'm not sure if this is entirely correct (especially not sure if the changes to `getSource` make sense...) but I at least have a prototype of `AlphaSourceWarped` that works with BigWarp 9's `WarpedSource`:

The behavior I get now:
![maybe-working-alpha-test](https://github.com/BIOP/bigdataviewer-biop-tools/assets/6912043/13412133-a274-49df-bb94-d80f7585c3d9)



> wreaks havoc in a lot of my repos regarding:
>    * concatenation of successive transforms
>    * making a source that blends many warped source efficiently

I'm sympathetic to that.  Especially if there will be many places and lots of code that's affected by this.  Perhaps it would have been better for WarpedSource to stay the way it was, and for this changes with different behavior to go to a new class  (`RealTransformedSource`? [see here](https://github.com/bigdataviewer/bigdataviewer-core/pull/133) ).  I don't know.  Will talk with @axtimwalde  this week.

**Comment by NicoKiaru** [comment]
Thanks for digging through this. 

>  Especially if there will be many places and lots of code that's affected by this.

I know that I have at least another demo that fails:

* https://github.com/BIOP/bigdataviewer-biop-tools/blob/master/src/test/java/fused/CrazyMultireWarpedSourcesFusedDemo.java

It's not self-contained (I'll try to make it self-contained) but it was looking like that:

https://github.com/BIOP/bigdataviewer-biop-tools/assets/20223054/f506b529-8ab3-4242-a4d2-11e9f816488d

Now the image is mostly black, even with the fix you suggested.

I have another demo where the 'fused sources' are not multi-resolution, and this works fine.

> Perhaps it would have been better for WarpedSource to stay the way it was, and for this changes with different behavior to go to a new class.

Thanks for considering it. I'll try to make some simple use-cases that could show clearly where I'm affected. I need to confirm this, but I feel like the new way of specifying the transform is now relative to another referential, and that this may break backward compatibility. Maybe it'll backward compatible in some cases, but for the general case, I'm not sure that the landmark coordinates will still be valid when one switches from BW 8 to BW 9 with the same landmark files.

Also, maybe that's a minor performance hit and it's not very relevant, but you need to compute two extra affine transforms per pixel if I understand correctly.

I'll try keep wou posted by the end of week and hopefully provide useful inputs.

**Comment by NicoKiaru** [comment]
> Perhaps it would have been better for WarpedSource to stay the way it was, and for this changes with different behavior to go to a new class (RealTransformedSource? https://github.com/bigdataviewer/bigdataviewer-core/pull/133 ). I don't know. Will talk with @axtimwalde this week.

@bogovicj have you discussed this ? Is the implementation going to stay like that ? If yes I need to seriously work on this bug. Are you sure the new implementation brings some benefits ?

**Comment by NicoKiaru** [comment]
I think this is fixed now. I'm not completely sure of the initial issue.

I rewrote the test.

The only remaining issue I have is thus: https://github.com/imglib/imglib2-realtransform/issues/45
