### ISSUE TITLE
Expose X Y and Z voxel sizes and confirm units

### ISSUE THREAD

**Issue by lacan** [BIOP/bigdataviewer-biop-tools#63]
In 
https://github.com/BIOP/bigdataviewer-biop-tools/blob/59eadd20e2d517f73eaff40ab40599bd03ef8b10/src/main/java/ch/epfl/biop/scijava/command/source/SourcesMakeModelCommand.java#L18
It requires an xy pizel size.
For testing it may be useful to separate x y and z

Moreover as teh GUI does not mention units, how do we know what to enter?

**Comment by NicoKiaru** [comment]
Changed in https://github.com/BIOP/bigdataviewer-biop-tools/commit/e6e9832695d20fc0611623e7735dedbd1052b228
